In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

HYPOTHESIS TESTING EXERCISES 

1) A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


# cutlets
     1)     * Ho ---> myu(unit A) = myu(unit B)     there is no significant difference between the 2 cutlets diameter
            * Ha ---> myu(unit A ) != myu(unit B )   there is a significant difference 

               IT IS A "2-SAMPLE 2-TAIL-T TEST"

In [4]:
cutlets=pd.read_csv(r"C:\Users\91863\Downloads\Cutlets.csv")
cutlets

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
cutlet_A =cutlets[["Unit A"]]
cutlet_A

Unit A
0   6.8090
1   6.4376
2   6.9157
3   7.3012
4   7.4488
5   7.3871
6   6.8755
7   7.0621
8   6.6840
9   6.8236
10  7.3930
11  7.5169
12  6.9246
13  6.9256
14  6.5797
15  6.8394
16  6.5970
17  7.2705
18  7.2828
19  7.3495
20  6.9438
21  7.1560
22  6.5341
23  7.2854
24  6.9952
25  6.8568
26  7.2163
27  6.6801
28  6.9431
29  7.0852
30  6.7794
31  7.2783
32  7.1561
33  7.3943
34  6.9405

In [6]:
cutlet_B =cutlets[["Unit B"]]
cutlet_B

Unit B
0   6.7703
1   7.5093
2   6.7300
3   6.7878
4   7.1522
5   6.8110
6   7.2212
7   6.6606
8   7.2402
9   7.0503
10  6.8810
11  7.4059
12  6.7652
13  6.0380
14  7.1581
15  7.0240
16  6.6672
17  7.4314
18  7.3070
19  6.7478
20  6.8889
21  7.4220
22  6.5217
23  7.1688
24  6.7594
25  6.9399
26  7.0133
27  6.9182
28  6.3346
29  7.5459
30  7.0992
31  7.1180
32  6.6965
33  6.5780
34  7.3875

In [7]:
statistics,pvalue = stats.ttest_ind(cutlet_A,cutlet_B)
statistics,pvalue

(array([0.72286887]), array([0.47223947]))

In [8]:
alpha = 0.05
if pvalue < alpha:
    print("REJECT H0. there is significant difference between the two units diameters of cutlets")
else:
    print("Accept Ho . therfore there is no significant difference between the two units diamters of cutlets")

Accept Ho . therfore there is no significant difference between the two units diamters of cutlets


---------

----

-----

2)     A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
  Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.
 


# ANOVA 

 DEFINING HYPOTHESIS statements
 *     Ho= all means are equal 
 *     Ha =  atleast one of them will have difference in average TaT among the 4 laboratories 

In [9]:
labtat=pd.read_csv(r"C:\Users\91863\Downloads\LabTAT.csv")
labtat

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [10]:
labtat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [11]:
import scipy.stats as stats
statistics,p_value = stats.f_oneway(labtat.iloc[:,0],labtat.iloc[:,1],labtat.iloc[:,2],labtat.iloc[:,3])

In [12]:
statistics,p_value

(118.70421654401437, 2.1156708949992414e-57)

In [13]:
alpha = 0.05
if p_value < alpha:
    print("REJECT Ho. there is evidence of a significant difference in average TAT among the laboratories.")
else:
    print("it is failed to reject Ho. no significant differnce in average TAT among the laboratories ")

REJECT Ho. there is evidence of a significant difference in average TAT among the laboratories.



*   p value is approximately "0".
* therefore p< alpha , so reject Ho
*     hence Ha is accepted concluding that atleast one of them will be different in the average Turn Around Time (TAT) of reports of the  4 laboratories 

-------

-----

----

3) Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [14]:
buyer = pd.read_csv(r"C:\Users\91863\Downloads\BuyerRatio.csv")
buyer

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

# CHI-SQUARE

DEFINING hypothesis statements
*            Ho = p1(male) = p2 (female)
*            Ha = p1 (male) != p2(female)

In [177]:
observed_data = [[50,142,131,70],[435,1523,1356,750]]
statistic,p_value,df,expected=chi2_contingency(observed_data)
statistic,p_value,df,expected

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [179]:
alpha=0.05
print(f"the value of p:{p_value}")
if p_value < alpha:
    print("Dependent: Reject Ho. So, The male- female ratios are not equal")
else:
    print("Independent: Accept Ho. So, the male-female ratios are Equal")

the value of p:0.6603094907091882
Independent: Accept Ho. So, the male-female ratios are Equal


-------
------

4)TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences



In [152]:
data = pd.read_csv(r"C:\Users\91863\Downloads\Costomer+OrderForm.csv")
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [160]:

philippines = data[["Phillippines"]]
philippines.value_counts()


Phillippines
Error Free      271
Defective        29
Name: count, dtype: int64

In [162]:
data[["Indonesia"]].value_counts()


Indonesia 
Error Free    267
Defective      33
Name: count, dtype: int64

In [163]:
 data[["Malta"]].value_counts()

Malta     
Error Free    269
Defective      31
Name: count, dtype: int64

In [166]:
data[["India"]].value_counts()

India     
Error Free    280
Defective      20
Name: count, dtype: int64

In [155]:
data_cross=pd.DataFrame(index =["Phillippines","Indonesia","Malta","India"],columns=["defective","non-defective"],copy=False)
data_cross

defective non-defective
Phillippines       NaN           NaN
Indonesia          NaN           NaN
Malta              NaN           NaN
India              NaN           NaN

In [165]:
data_cross["non-defective"]=[271,267,269,280]
data_cross["defective"]=[29,33,31,20]
data_cross

defective  non-defective
Phillippines         29            271
Indonesia            33            267
Malta                31            269
India                20            280

CHI-SQUARE method

*    Ho = independent  i.e , defective %  are equal in  all centre
*    Ha = dependent   i.e., defective % is not equal

In [167]:
from scipy.stats import chi2_contingency

In [169]:
observed=[[29,271],[33,267],[31,269],[20,280]]
print(chi2_contingency(observed))

Chi2ContingencyResult(statistic=3.8589606858203545, pvalue=0.27710209912331435, dof=3, expected_freq=array([[ 28.25, 271.75],
       [ 28.25, 271.75],
       [ 28.25, 271.75],
       [ 28.25, 271.75]]))


In [172]:
stat,p_val,df,expected=chi2_contingency(observed)
stat,p_val,df,expected

(3.8589606858203545,
 0.27710209912331435,
 3,
 array([[ 28.25, 271.75],
        [ 28.25, 271.75],
        [ 28.25, 271.75],
        [ 28.25, 271.75]]))

In [174]:
# p-value
alpha=0.05
print(f"the value of  p is :{p_val}")
if p_val < alpha :
    print("dependent: Reject Ho. So, all the centres are not equal")
else:
    print("Independent : Accept Ho So , all the centres are equal in defective %")

the value of  p is :0.27710209912331435
Independent : Accept Ho So , all the centres are equal in defective %
